version: "3"

services:
  db:
    container_name: MYSQL
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      timeout: 10s
      retries: 10
      start_period: 1s
    volumes: 
      - "./db:/docker-entrypoint-initdb.d"

  api:
    image: node:16
    container_name: Node_Api
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
    environment:
      - APP_PORT=3333
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=cep_lookup
    ports:
      - 3333:3333

networks:
  default:
    name: sql_net
