version: "3"

services:
  db:
    container_name: MYSQL
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      timeout: 10s
      retries: 10
      start_period: 1s
    volumes: 
      - "./db:/docker-entrypoint-initdb.d"

networks:
  default:
    name: sql_net